pipeline {
    agent any 
    environment {
        dockerHubRegistry = 'jinjoo0402/s4_fastapi'
        DOCKERHUB_CREDENTIALS = credentials('DOCKER_HUB_TOKEN') 
        EC2_CREDENTIALS = credentials('PYTHON_EC2_SSH_KEY') 
        dockerHost = 'ssh://ubuntu@j10e206a.p.ssafy.io'
    }
    stages {
        stage('Checkout Application Git Branch') {
            steps {
                git credentialsId: 'GITLAB_TOKEN',
                    url: 'https://lab.ssafy.com/s10-bigdata-dist-sub2/S10P22E206.git',
                    branch: 'fastapi'
            }
            post {
                failure {
                    echo 'Repository clone failure !'
                }
                success {
                    echo 'Repository clone success !'
                }
            }
        }
        stage('Docker Image Build') {
            steps {
                dir('./backend/python/singsongsangsong') {
                    sh "sudo docker build . -t ${dockerHubRegistry}:${currentBuild.number}"
                    sh "sudo docker build . -t ${dockerHubRegistry}:latest"
                }
            }
            post {
                failure {
                    echo 'Docker image build failure !'
                }
                success {
                    echo 'Docker image build success !'
                }
            }
        }
        stage('Login') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('Docker Image Push') {
            steps {
                sh "docker push ${dockerHubRegistry}:${currentBuild.number}"
                sh "docker push ${dockerHubRegistry}:latest"
                sleep 5
            }
            post {
                failure {
                    echo 'Docker Image Push failure !'
                    sh "docker rmi ${dockerHubRegistry}:${currentBuild.number}"
                    sh "docker rmi ${dockerHubRegistry}:latest"
                }
                success {
                    echo 'Docker image push success !'
                    sh "docker rmi ${dockerHubRegistry}:${currentBuild.number}"
                }
            }
        }
        stage('Deploy') {
            steps {
                sshagent (credentials: ['PYTHON_EC2_SSH_KEY']) { 
                    sh 'docker ps -f name=fastapi-service -q \
                    | xargs --no-run-if-empty docker container stop'
                    sh 'docker container ls -a -f name=fastapi-service -q \
                    | xargs -r docker container rm'
                    sh "docker run -d --name fastapi-service -p 8000:8000 ${dockerHubRegistry}:latest"
                }
            }
            post {
                failure {
                    echo 'fastapi deployment failure !'
                }
                success {
                    echo 'fastapi deployment success !'
                }
            }
        }
    }
}
